### PR TITLE
simple selector fetching https://app.clickup.com/t/866aga82t

### PR DESCRIPTION
**Pull request by maaislam**

### CODE REVIEW

**Comment by maaislam** [comment]
Please see the parent task in ClickUp 
[parent task](https://app.clickup.com/t/866a18efr)

**Comment by wilsonweb** [comment]
Overall I like this. One thing that I have seen is that there are times when an element is legitimately never in the DOM and we clutter the browser console with errors that make us look bad. I worry that it will be too easy for developers in the future to forget that every time they call this method they need to specify a catch(). A 3rd parameter (optional) could be added that allows it to simply return a null rather than a reject. An alternative would be to create a wrapper for this method called getElementOrNull() that would contain the catch.

This is just an idea, on one of the HPE sites I see some selectors for turbo blowing up the console log from time to time.

**Comment by maaislam** [comment]
@wilsonweb 
please check the latest commit. I have tried to address your concerns.

**Review by maaislam — COMMENTED** [review]
@wilsonweb if you are happy with the changes.
Please merge to the main branch. GitHub won't let me as I am the Author of the PR

**Pull request closed without merging**
